apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    tier: db-tier
    type: back-end
spec:
  containers:
    - name: postgres
      image: postgres
      env:
        -  name: POSTGRES_PASSWORD
           value: mysecretpassword

    - name: hello-world
      image: hello-world